name: Update README

on:
  schedule:
    - cron: '0 8 * * *' # 3 AM ES
  workflow_dispatch:

  jobs:
    update-readme:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Set up Python 
          uses: actions/setup-python@v2
          with:
            python-version: latest

        - run: Run Python Script
          run: python update.py


        
